### ISSUE TITLE
Chat: No text shown in message boxes

### ISSUE THREAD

**Issue by johannt-dev** [nifty-gui/nifty-gui#293] opened 2014-10-13 13:39 UTC
Heya!
I need some help with the Nifty-Chat. So I got the following in my XML:

``` XML
<control id="chat1" name="nifty-chat" width="50%" height="50%" lines="14" sendLabel="Send"/>
```

... And this in java:

``` JAVA
@NiftyEventSubscriber(id="chat1")
    public final void onSendText(final String id, final ChatTextSendEvent event) {
        final Chat chat = screen.findNiftyControl(id, Chat.class);
        chat.receivedChatLine(event.getText(), null, null);
    }
```

![chat](https://cloud.githubusercontent.com/assets/6951970/4617934/be0e3b7e-5304-11e4-8741-3637d0393771.png)

The chat over all is working properly, except that there are no messages in the chatboxes, while these are shown. Also the player is shown. And the message I type is also there, but maybe not delivered correctly? o.o

Greetz.

**Comment by relu91** [comment] 2014-10-15 17:06
I can confirm that the chat is not working at all...

**Comment by ghost** [comment] 2014-10-15 17:28
It seems that there is currently no xml argument available to pass a font to the chat. However, I couldn't spot a way in Java either. Is there some kind of workaround for setting a font in a complex control like a chat? Or do we just have to wait for someone to fix this/write our own chat?

**Comment by oberien** [comment] 2014-10-15 20:26
Why does the chat actually use a label-control for each message and not a text? Is there a special reason for that?

**Comment by oberien** [comment] 2014-10-20 20:08
Will this be fixed soon, or is it better for us to implement an own chat?

**Comment by bgroenks96** [comment] 2014-10-20 20:15
Do you have a working example (like a unit test) that I can use to reproduce the bug? I can try to take a look, I just don't have time to go putting together an entire setup program to test it.

**Comment by oberien** [comment] 2014-10-20 20:25
@relu91 seemd to have a kind of sscce as he could aprove the bug. We don't have a small example, as it's integrated into our big project...
Maybe I can get Hightek to create a sscce, maybe in the next few days, hopefully tomorrow.
But maybe relu already has one.

**Comment by bgroenks96** [comment] 2014-10-20 21:37
If @relu91 has one or at least an easily extrapolated one that would be great. I just don't have time right now to set one up.

If someone can post one for me though, I will prioritize putting a patch out ASAP (assuming I can find the bug :worried: )

**Comment by oberien** [comment] 2014-10-20 21:42
hightek is working on an sscce and may post it today or tomorrow (CEST), but surely in the next 24 hours. It will requuire lwjgl, slick2d and nifty as it seems atm.

Like we already stated we might think it could be a bug having to do with fonts.

**Comment by relu91** [comment] 2014-10-21 09:31
I used jmonkeyengine to test it, nothing special just a simple class with a controller that does what @HigHt3k  said. Here it goes:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nifty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://nifty-gui.lessvoid.com/nifty-gui" xsi:schemaLocation="https://raw.githubusercontent.com/void256/nifty-gui/1.4/nifty-core/src/main/resources/nifty.xsd https://raw.githubusercontent.com/void256/nifty-gui/1.4/nifty-core/src/main/resources/nifty.xsd">
    <useControls filename="nifty-default-controls.xml"/>
    <useStyles filename="nifty-default-styles.xml"/>
    <screen id="GScreen0" controller="mygame.Main">
        <layer id="GLayer0" childLayout="center">
            <control name="nifty-chat" id="chat1" height="50%" width="50%" sendLabel="Send" lines="10"/>
        </layer>
    </screen>
</nifty>
```

and the class

``` java
import com.jme3.app.SimpleApplication;
import com.jme3.niftygui.NiftyJmeDisplay;
import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.NiftyEventSubscriber;
import de.lessvoid.nifty.controls.Chat;
import de.lessvoid.nifty.controls.ChatTextSendEvent;
import de.lessvoid.nifty.screen.Screen;
import de.lessvoid.nifty.screen.ScreenController;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Main extends SimpleApplication implements ScreenController {

  public static void main(String[] args) {
      Logger.getLogger("de.lessvoid").setLevel(Level.ALL);
    Main app = new Main();
    app.start();
  }
    private Nifty nifty;
    private Screen screen;

  public void simpleInitApp() {
        System.out.println(Logger.getLogger("de.lessvoid").getLevel());

        NiftyJmeDisplay niftyDisplay = new NiftyJmeDisplay(assetManager,
                                                          inputManager,
                                                          audioRenderer,
                                                          guiViewPort);
        nifty = niftyDisplay.getNifty();

        nifty.fromXml("Interface/test.xml", "start", this);

        // attach the nifty display to the gui view port as a processor
        guiViewPort.addProcessor(niftyDisplay);

        Logger.getLogger("de.lessvoid").setLevel(Level.ALL);
        inputManager.setCursorVisible(true);
    }

    public void bind(Nifty nifty, Screen screen) {
        System.out.println("bind( " + screen.getScreenId() + ")");
        this.screen = screen;
        final Chat chat = screen.findNiftyControl("chat1", Chat.class);
        chat.addPlayer("Cris", null);
        chat.update();
    }

    public void onStartScreen() {

        System.out.println("onStartScreen");


    }

    public void onEndScreen() {
        System.out.println("onEndScreen");
    }

    public void quit(){
        nifty.gotoScreen("end");
    }

    @NiftyEventSubscriber(id="chat1")
    public final void onSendText(final String id, final ChatTextSendEvent event) {
        final Chat chat = screen.findNiftyControl(id, Chat.class);
        chat.receivedChatLine(event.getText(), null, null);
        chat.update();

    }
}
```

In my tests no player or text is shown.

**Comment by bgroenks96** [comment] 2014-10-21 15:57
Thank you @relu91 I will try to look into this in the next few days.

I will probably try converting your JME base code to JOGL or LWJGL so that I don't have to setup JME (I don't have it setup right now :disappointed: ), but I will do both if necessary.

And if I can't figure out what's going on, hopefully @void256 will be able to :worried:

**Comment by bgroenks96** [comment] 2014-10-22 16:30
It seems ChatControl was deprecated by @mkaring 

This might mean it is best for you guys to build your own ChatControl, unless @mkaring can tell us if there is a replacement for the deprecated ChatControl class somewhere that I don't know about?

I'm going to keep investigating the issue, and if I can find the problem I might go ahead and push a fix for ChatControl while it still exists in the controls library.

I'll leave the decision up to you as to whether or not you want to use depcrecated code (whether or not it's meant to be deprecated, however, is still a little unclear to me).

**Comment by relu91** [comment] 2014-10-22 18:19
I chat control could be very useful in games.... I vote to keep it update!

**Comment by bgroenks96** [comment] 2014-10-22 19:16
I encountered a git issue when trying to push partial changes to the master branch, so I went ahead and just pushed my changes upstream in my forked repo. The fix for this issue will be included in the merge for that pull request.

**Closed as completed** 2014-10-22 19:20 UTC
Labels: needs fix

**Comment by oberien** [comment] 2014-10-22 19:27
GG I LOVE YOU!!! :D

**Comment by oberien** [comment] 2014-11-09 10:02
The chat is buggy anyways in several cases. I think I might need to rewrite it, or using the existing create an own new controller...

If a message over several lines is displayed, the next chat message is on top of the 3rd line of the message before. A horizontal scrollbar appears, even though it isn't needed.
The vertical scrollbar doesn't work for me.
if a custom number of lines is used for the chat, the input textfield will be on top of the chat.

etc.

**Comment by void256** [comment] 2014-11-09 11:52
FWIIW

I've finally interviewed @mkaring about why he deprecated it on IRC. Here is what he said:

```
<void256> Nitram__: people are curious why you deprecated the chatcontrol in 1.4 ..
can you remember? I think it was because it sucked too much xD
<Nitram__> void256: Because it does not work :D And it is far too specified for
a single control
<Nitram__> at least in my opinion
<Nitram__> a "chat control" is really not something that is required in the default controls.
This is at least my opinion
```

So, that was the reason. I think he is right.

Maybe in 2.0 we should move it into some example/demo project instead so that people can use it as some form of blueprint but concentrate on more important, more general controls that we publish directly with Nifty?

But that's not set in stone yet ... I think for now we should keep it in 1.4 despite it's obvious problems. As always help is very welcome!

**Comment by oberien** [comment] 2014-11-09 12:48
I need to create a new Chat Control (or something similar) anyways, no matter what happens. I think I will start with the existing one and use the code of the current as base for mine.

If I get everything to work like expected, I may try to change the current nifty-chatcontrol to equal mine, if you wish :)

In case I get it working (i really don't know how whether i can do it) and include it into the current nifty, I would like to keep it inside the default controls as it is something a lot of GUI-users using nifty will need and use. Especially because nifty is used for games-programming I find it inportant having a chat or something similar.
