### ISSUE TITLE
Crash when use nifty.closePopup(popup.getId());

### ISSUE THREAD

**Issue by akariam** [nifty-gui/nifty-gui#127] opened 2013-07-01 18:40 UTC
Hi,

I have an issue with the method closePopup. When I call it, the application crash...
I don't know what's going on, here the error message:

juil. 01, 2013 7:35:08 PM com.jme3.app.Application handleError
SEVERE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:371)
    at java.util.ArrayList.get(ArrayList.java:384)
    at de.lessvoid.nifty.controls.FocusHandler.popState(FocusHandler.java:161)
    at de.lessvoid.nifty.screen.Screen$ElementWithEndNotify.remove(Screen.java:800)
    at de.lessvoid.nifty.screen.Screen.processAddAndRemoveLayerElements(Screen.java:569)
    at de.lessvoid.nifty.Nifty.removeLayerElements(Nifty.java:333)
    at de.lessvoid.nifty.Nifty.handleDynamicElements(Nifty.java:314)
    at de.lessvoid.nifty.Nifty.update(Nifty.java:253)
    at com.jme3.niftygui.InputSystemJme.endInput(InputSystemJme.java:113)
    at com.jme3.input.InputManager.processQueue(InputManager.java:821)
    at com.jme3.input.InputManager.update(InputManager.java:885)
    at com.jme3.app.Application.update(Application.java:606)
    at com.jme3.app.SimpleApplication.update(SimpleApplication.java:230)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
    at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
    at java.lang.Thread.run(Thread.java:722)

**Comment by void256** [comment] 2013-07-02 19:46
Can you provide a SSCCE for this issue? Looks like the popup is maybe closed twice or something similar. Some example code on how you create, display and finally close the popup might help.

And please send the String that nifty.getVersion() returns so that I know what Nifty version you're using.

**Comment by akariam** [comment] 2013-07-02 20:16
popup= nifty.createPopup("waiting");
public void simpleUpdate(float tpf) {
        if (!startScreen.paused) {
            startScreen.setEnabled(false);
            flyCam.setDragToRotate(false);
            ss.setEnabled(true);
            ss.zoomLevell = startScreen.zoomLevel;
            ss.useSat = startScreen.useSat;
            ss.showWaypoints = startScreen.showWaypoints;
            ss.flightData = startScreen.flightData;
            ss.aircraft = startScreen.aircraft;
            ss.useData = startScreen.useData;
            ss.filePath = startScreen.filepath;
            startScreen.paused = true;
        }
        ss.numbsim2=startScreen.numbsim;

```
    if((ss.aircraft!=null)&&(ss.numbsim2!=0)&&(createpop)){
        ss.numbsim=ss.numbsim2;
        ss.speedMultiplier=1;
        ss.speedBase=1;
        ss.collisionCountTot=0;
        popup.findNiftyControl("percent", Label.class).setText(Integer.toString((int)((ss.numbsim2-ss.numbsim)*100/ss.numbsim2)) + " % done");      
        nifty.showPopup(nifty.getCurrentScreen(),popup.getId(), popup);
        createpop=false;
    }

    if((ss.numbsim!=1)&&(ss.done)&&(ss.numbsim!=0)&&(!createpop)){
        ss.statsim();
        ss.numbsim--;
        popup.findNiftyControl("percent", Label.class).setText(Integer.toString((int)((ss.numbsim2-ss.numbsim)*100/ss.numbsim2)) + " % done");
        ss.done=false;
    }

    else if ((ss.done)&&(ss.numbsim==1)){
        ss.done=false;
        createpop=true;
        ss.cleanup();
        this.getStateManager().detach(ss);
        startScreen.setEnabled(true);
        nifty.closePopup(popup.getId());  //this is where the program crash *******************************************
        startScreen.goToDone2(ss.aircraftCount, ss.collisionCount, ss.dm.angleOfImpact, ss.dm.throwDistance, ss.dm.widthOfField, ss.dm.terminalVelocity, ss.dm.timeToImpact,ss.nbsimimpact); 
    }

    else if ((ss.done)&&(ss.numbsim==0)) {
        ss.done = false;
        ss.aircraft=null;
        flyCam.setDragToRotate(true);
        ss.setEnabled(false);
        ss.cleanup();
        this.getStateManager().detach(ss);
        startScreen.setEnabled(true);
        startScreen.goToDone(ss.aircraftCount, ss.collisionCount, ss.dm.angleOfImpact, ss.dm.throwDistance, ss.dm.widthOfField, ss.dm.terminalVelocity, ss.dm.timeToImpact);
    }

    if (startScreen.runAgain) {
        startScreen.runAgain = false;
        startScreen.cleanup();
        this.getStateManager().detach(startScreen);     
        this.getStateManager().attach(this.startScreen);
        this.getStateManager().attach(this.ss);
    }
}
```

This is an extract of my code.
There is not a nifty.getVersion() method...

**Comment by void256** [comment] 2013-07-04 21:37
nifty.getVersion() was introduced in Nifty 1.3.1 (I think) so you're using some old version of Nifty (probably because of the jme3 version you use). There have been some popup related fixed in later Nifty versions but I'm not sure if that exact same problem of yours was a part of these fixes :/ Using a nightly build of jme3 would give you Nifty 1.3.3 which might be worth a try to see if the problem eventually disappears.

About your code example: Well I've tried to read and understand it but I was too confused by it so I failed in understanding it unfortunately. Can you try to isolate the Nifty related things from your code? Like show a popup and then close it again and see it that works? It might be the order in which you call things but I can't really decipher it from your code :/

If you could reduce it to the absolute minimum source that still has the problem and send me a simple self contained correct example I'm sure we could trace down this issue and solve it.

**Comment by philipwhiuk** [comment] 2013-07-14 12:57
Formatted the sample code.

``` java
popup = nifty.createPopup("waiting");
public void simpleUpdate(float tpf) {
      if (!startScreen.paused) {
            startScreen.setEnabled(false);
            flyCam.setDragToRotate(false);
            ss.setEnabled(true);
            ss.zoomLevell = startScreen.zoomLevel;
            ss.useSat = startScreen.useSat;
            ss.showWaypoints = startScreen.showWaypoints;
            ss.flightData = startScreen.flightData;
            ss.aircraft = startScreen.aircraft;
            ss.useData = startScreen.useData;
            ss.filePath = startScreen.filepath;
            startScreen.paused = true;
      }
      ss.numbsim2=startScreen.numbsim;
      if((ss.aircraft!=null)&&(ss.numbsim2!=0)&&(createpop)){
            ss.numbsim=ss.numbsim2;
            ss.speedMultiplier=1;
            ss.speedBase=1;
            ss.collisionCountTot=0;
            popup.findNiftyControl("percent", Label.class)
                .setText(Integer.toString((int)((ss.numbsim2-ss.numbsim)*100
                             /ss.numbsim2)) + " % done");      
            nifty.showPopup(nifty.getCurrentScreen(),popup.getId(), popup);
            createpop=false;
       }
    if((ss.numbsim!=1)&&(ss.done)&&(ss.numbsim!=0)&&(!createpop)){
        ss.statsim();
        ss.numbsim--;
        popup.findNiftyControl("percent", Label.class)
                 .setText(Integer.toString((int)((ss.numbsim2-ss.numbsim)*100
                            /ss.numbsim2)) + " % done");
        ss.done=false;
    }

    else if ((ss.done)&&(ss.numbsim==1)){
        ss.done=false;
        createpop=true;
        ss.cleanup();
        this.getStateManager().detach(ss);
        startScreen.setEnabled(true);
        nifty.closePopup(popup.getId());  //this is where the program crash 
        startScreen.goToDone2(ss.aircraftCount, ss.collisionCount, 
                     ss.dm.angleOfImpact, ss.dm.throwDistance, 
                     ss.dm.widthOfField, ss.dm.terminalVelocity,                 
                     ss.dm.timeToImpact,ss.nbsimimpact); 
    }

    else if ((ss.done)&&(ss.numbsim==0)) {
        ss.done = false;
        ss.aircraft=null;
        flyCam.setDragToRotate(true);
        ss.setEnabled(false);
        ss.cleanup();
        this.getStateManager().detach(ss);
        startScreen.setEnabled(true);
        startScreen.goToDone(ss.aircraftCount, ss.collisionCount, 
                    ss.dm.angleOfImpact, ss.dm.throwDistance, ss.dm.widthOfField, 
                    ss.dm.terminalVelocity, ss.dm.timeToImpact);
    }

    if (startScreen.runAgain) {
        startScreen.runAgain = false;
        startScreen.cleanup();
        this.getStateManager().detach(startScreen);     
        this.getStateManager().attach(this.startScreen);
        this.getStateManager().attach(this.ss);
    }
}
```

**Comment by void256** [comment] 2013-07-14 16:01
Thanks @philipwhiuk but the real problem is the logic here :wink: I can't figure out in what order Nifty methods are called so that I can reproduce this problem.

**Comment by void256** [comment] 2014-05-02 20:51
I'm sorry but I didn't understand the example code provided and I haven't found a way to reproduce the issue.

I'll close this issue for now. Please re-open if this still is a problem!

**Closed as completed by void256** 2014-05-02 20:51 UTC
