### ISSUE TITLE
Proposal for improved layouting

### ISSUE THREAD

**Issue by mkaring** [nifty-gui/nifty-gui#349] opened 2015-07-19 11:31 UTC
Hello,

I'd like push some ideas for a improved layouting system for Nitfy 2.0.

The idea is to remove layout logic from NiftyNode and the layout implementation and move it to the Nifty-Controls to allow complex and custom layout controls. The NiftyNode itself, while being able to store and maintain children, isn't accepting any children unless there is a attached control that explicitly allows one or multiple children to be set. This requires any panel to become a control.

The layouting process itself would be a two stage operation. The data storage for the basic values that are required for rendering and for the layout of all kinds of elements would be stored in the NiftyNode. Any layouting data that is required for more complex layouting has to be stored in the control.

The layouting itself happens in two top down passes. The first one is measuring the controls, generating desired size. For the measuring the layouter sends the size available to the root node. The default implementation of each child node would assume the desired size to be the size reported as available. That is in case no control is attached. The controls have to be able to overwrite this. For example a label would use the size of it's text as desired size. As the measuring step passes the size available down in each step a label can choose to honor the available width to calculate line text wrapping. The layouter doesn't actually measure the entire tree down. It only measures the root element. Measuring the children is the task of the controls that claim to accept children. Now what such a control would do is to measure each element based on the available size for the content control and the nature of the child arrangement. For example a scroll panel that is only allowed to scroll horizontal could offer the child a infinite horizontal space and a vertical space that is set to the height of the parent control minus the size of the scroll bar, A uniform grid arragement could easily split the available size into equal parts and send those smaller sizes to the children of the element. The order how the children are measured is fully up to the control that does the measuring. Also if it uses the measuring results of one child to effect another is up to the measuring. The size desired for a element may also be larger than the size available. For example if a label is rendered and the size available is not sufficient to write down the text the label may report a larger desired size. The outer layout control is then able to react on that information or ignore it. Now if any change is applied to the control that may cause the size of the control to change the measure is invalidated. This flag is stored in the NiftyNode. A invalid measuring is reported to the parent of each control up to the root. With the root having a invalid measure the layouter has to trigger the measuring pass again at the next update of the UI. The content controls measure their children again and can choose if they measure children that are still valid again or if they don't. Even if a control is unaffected by the measure change of the child it still sets it's parent to invalid. The layouter ONLY triggers the measure pass if the root is set to invalid.
Now all that largely assumes that the sizes are not set to fixed values. But it works also with fixed values. With fixed values the controls can't be streched or sized down. And need to be placed within the available size according to their alignment.

So much for the first stage of the layouting. The second stage is the actual placement if a element within it's parent element. This stages requires all elements to have valid measurement values. A run of the measurement pass causes the placement to be invalid if the sizes change. The valid flag of the placement is handled in exactly the same way as the measurement flag. The placement too is triggered by the layouter on the root element and the child elements arrange their children on their own. The sizes in this pass are not up for debate anymore. No element must exceed the size applied to them. Basically in this pass each element receives the placement data from the parent. That is the x and y coordinate along with the size. Those values have to be used for the size. How ever it is up to each element to forward the values to their children and place them within the bounds using the measurement values as they see fit. So this is the stage where a panel that layouts it's children in a grid actually places the children in a grid structure. The placement stage is handled separately to keep the code clean and to allow operations that only invalidate the placement, such as scrolling a element.

This concept removes most of the layouting logic from the layouter and transfers it to the controls. Allowing much more complex and customizable layouts. And this is very Nifty. ;-)

Now unless someone is shouting: Are you mental?! You can't do that! I will go ahead and try to implement a working implementation in the Nifty-2.0 branch. Any suggestions are welcome.

What do you think?

**Comment by void256** [comment] 2015-07-19 14:06
**ARE YOU MENTAL TRYING TO MESS WITH THE LAYOUTER?** :anguished: :wink: :laughing: 
I would say, feel free to go ahead! :sunglasses: 

However, there are some things I'd like you to consider:

##### 1. Keep the, old simple layouts as an option or optional feature maybe?

I still like the simplicity of the current layout. Define a childLayout for the parent and maybe have some constraints for the children (like alignment, percent sizes and so on). Easy, clean and yes, limited :wink: but still, sometimes this is all you need.

Do you see a way to keep that besides the new way?

##### 2. Seperate the layout algorithm in a separate package

Currently the core implementations of the childLayouts is kept nicely in the `de.lessvoid.nifty.internal.layout` package and they all have unit tests.

The actual layout algorithm, however, is currently hidden in the NiftyNode - which is quite unfortunate :disappointed:

Can we improve that with the new layouter, like make that a module/component of some sort inside of Nifty?

##### 3. The NiftyNode tree might change soon ...

This is something that bothers me for a while now. The 2.0 NiftyNode is turning out to be another hero class, like the Element class in 1.x.

Currently it has a lot of responsibility:
- Maintain the parent/child relationship
- Do all the input event processing
- Perform the layout
- Keeps the NiftyCanvas and tracks which parts need to be redrawn and updated
- Some special NiftyNode instances are parent nodes with some additonal features
- Keep the IntervalAnimators and call them regulary when needed
- Keep the current transformation matrix for that node
- Keep the node state and the associated CSS properties
- Keep all the backgroundColor/Gradient/Layout properties

Waaah, that is a lot and I'm not too happy with that. @bgroenks96 complained about that too :smile:

I'm thinking about changing that and actually this is something that blocks my progress right now. The thing is, I've read the paper [Toolkit Design for Interactive Structured Graphics](http://www.cs.umd.edu/hcil/jazz/learn/Toolkit_Design_2004.pdf) where they propose something they call polylithic toolkits where they combine multiple simple nodes into a scenegraph. Monolithic toolkits (their name) on the other hand use big base classes like Swing or JavaFX which are meant to be extended from.

NiftyNode doesn't really fit into one of both categories but still, it made me think if the big hero (monster) NiftyNode approach is the right way to go.

For instance the whole transformation matrix stuff could be extracted into a NiftyTransformationNode that keeps only the transformation matrix. And you only insert that node into your Nifty scenegraph when you need to modify the position, scale or rotation of a node (or its child nodes)! Otherwise you don't need all of that information in your scene graph at all! (Please note that the transformation is separated from the layout. So you'll do the layout and then on top you could use the transformation matrix to move / animate stuff around ...)

You could have like a NiftyCanvasNode, a NiftyLayoutNode and so on ... you get the idea. Separated concerns into dedicated nodes. Each of the nodes provide a little bit of functionality and the user can add it into his scenegraph only where it's needed instead of carrying it with a big NiftyNode everywhere.

The cost would be that the tree would contain more nodes in the end.

However, I still think we could abstract most of that away into invidiual NiftyControl nodes that themself create and manage sub trees of these smaller nodes but present themself as a single Node to the outside.

I'm only mentioning this so that you can expect that the whole NiftyNode tree based approach might change a bit in the future .. and I'm not yet sure how it will look :smile:

So there might be additional work ahead ... but you should still go ahead and try your changes now. Maybe keep in mind that some things will change and maybe abstract your new stuff out of the existing NiftyNode hierachy as best as you can?

**Comment by mkaring** [comment] 2015-07-19 14:50
My idea was to completely replace the old layouter and provide replacements to the current layouts for the new system. So you'd have a horizontal and vertical stacking panel that would replace the horizontal and vertical child layout. So the only difference is that you have to use a specific control instead of the child layout definition. I don't think any "half" solution is good for Nifty 2.0.

For those layouts I only want to add the two dirty flags and the dummy layout functions to the NiftyNode. Altering the Node itself is another task. I'd also like this one to change because I don't see the point of this 1-to-1 relation with the control. But that is something for another issue.

**Comment by void256** [comment] 2015-07-19 17:41
Sounds great then!

And when I understand you right, it will fit nice with what I have in mind for a better NiftyNode tree too! Great!

**Comment by bgroenks96** [comment] 2015-07-19 19:19
> You could have like a NiftyCanvasNode, a NiftyLayoutNode and so on ... 

Exactly. The layout should be handled by a separate node that NiftyNodes delegate to. I think, however, and you can correct me if I'm wrong, everything Martin said should be compatible with that design.

Maybe it can be a little bit like 'LayoutManager' in AWT/Swing, but hopefully a lot less horrible :wink:

**Comment by relu91** [comment] 2016-01-12 13:41
@mkaring I've found this discussion and I think it's the perfect place to speak about layout node, isn't it? 
Now that I read this most of my doubts are gone. I really like the flexibility you designed in this new system!! Even if now it's a bit too verbose, I think that most of the complexity could be hided in the controls logic which is more amazing. :+1:  Maybe the addition of the reference node it's too specific, if I would like to reference a lot of nodes the tree will be full of them. Could we add an option reference id in each node? 

Finally the issue that I've found so far:

With these tree:

``` java
 de.lessvoid.nifty.node.AlignmentLayoutNode@794baafe
    (NiftyBackgroundColorNode) backgroundColor [#00ffffff {0.0, 1.0, 1.0, 1.0}]
      (NiftyReferenceNode) id [alignmentNode]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@4d5825d6
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#ff0000ff {1.0, 0.0, 0.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@561c2c45
          (NiftyBackgroundColorNode) backgroundColor [#008000ff {0.0, 0.501960813999176, 0.0, 1.0}]
            (FixedSizeLayoutNode) width [100.0px] height [100.0px]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@539e922d
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#0000ffff {0.0, 0.0, 1.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@4f8ef33e
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#ffff00ff {1.0, 1.0, 0.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
```

I would expect that the background of the gui is #00ffffff but it's not set.

If I add a trasformation node like this:

``` java
root
  de.lessvoid.nifty.node.AlignmentLayoutNode@4421972b
    (NiftyTransformationNode) pivotX [0.5] pivotY [0.5] angleX [0.0] angleY [0.0] angleZ [10.0] scaleX [1.0] scaleY [1.0] scaleZ [1.0] posX [0.0] posY [0.0] posZ [0.0]
      (NiftyReferenceNode) id [alignmentNode]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@3a70f2db
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#ff0000ff {1.0, 0.0, 0.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@4d5825d6
          (NiftyBackgroundColorNode) backgroundColor [#008000ff {0.0, 0.501960813999176, 0.0, 1.0}]
            (FixedSizeLayoutNode) width [100.0px] height [100.0px]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@561c2c45
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#0000ffff {0.0, 0.0, 1.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
        de.lessvoid.nifty.node.AlignmentLayoutChildNode@539e922d
          (FixedSizeLayoutNode) width [100.0px] height [100.0px]
            (NiftyBackgroundColorNode) backgroundColor [#ffff00ff {1.0, 1.0, 0.0, 1.0}]
              (NiftyContentNode) width [0] height [0]
```

I would expect that the layout is rotated rigidly along the Z axis but it's not. Also scale transform breaks the layout.

I write the issues here because I don't know if they are actually bug or they are caused by my lack of knowledge!

**Comment by mkaring** [comment] 2016-01-12 15:02
Okay seems the alignment layout nodes still lack the `toString` methods.

Now to your issues:
You have to understand one thing: The _only_ thing that renders anything are the `NiftyContentNode`s. Everything else is just changing states. The coloured background is not rendered, because there is no `NiftyContentNode` to do so. The way to solve this is:

```
(NiftyBackgroundColorNode) backgroundColor [#00ffffff {0.0, 1.0, 1.0, 1.0}]
  (NiftyContentNode) <-- Insert That!
    (NiftyReferenceNode) id [alignmentNode]
```

The content node will render everything above it in the tree and cover the area of the parent layout node. So this one will cover the same surface as the `AlignmentLayoutNode` (so everything) and get the colour you set just before.

Regarding `NiftyTransformationNode`: I have no clue :D This should change the matrix, but those changes only affect the content nodes as far as I understand. But that is @void256 doing. He can explain what is happening these controls.

**Comment by void256** [comment] 2016-01-12 22:58
`NiftyTransformationNode` is basically the same as `NiftyBackgroundColorNode` - just another state changing node that will change the "transformation state". When the `NiftyContentNode` is reached the then current "transformation state" is applied. This should already work.

However the renderer where the tree will be resolved and is translated into something that Nifty can actually render is still heavily under development.

**Comment by void256** [comment] 2016-02-06 14:13
Can we actually close this issue now or are there still things that need to be discussed in here? The new layout process is in place thanks to @mkaring so can I go ahead and close this?

**Closed as completed** 2016-02-07 12:23 UTC
Labels: consider this for 2.0, enhancement, Nifty 2.0
