### ISSUE TITLE
Questions about Nifty's EventConsumption

### ISSUE THREAD

**Issue by oberien** [nifty-gui/nifty-gui#298] opened 2014-11-02 09:02 UTC
As the given Input forwarder for whatever reason are not working for our project, I implemented a custom one. First I forward them  to nifty and buffer them for slick. Then I would like to let nifty consume the events it uses. After that I handle the not consumed ones in slick.

For cosuming I saw that this should be done in nifty.update(). Is this information correct? Are all events handled by Nifty during the update method?

Second I would like to ask, which events are consumed by nifty. For the MouseEvents I think, that only the ones handled by the current ScreenController are consumed, but for the MouseEvents I don't have an idea.
Could you please confirm and explain, which events are consumed when by Nifty?

Kind Regards,
BH16

**Comment by bgroenks96** [comment] 2015-01-06 05:17
When you register a method with an element via the `<interact onClick="methodName">` tag, you can make the return type of that method `boolean` and return `true` to consume the event.

Basically Nifty's event handling will just walk up the element tree until one of the specified methods returns `true` to consume the event or it gets back to the ScreenController.

As for your question about `nifty.update`, I believe the answer is sort of yes and no. Yes in the sense that calling the update method is what triggers Nifty to process events, no in the sense that it is not a gurantee that it will _finish_ processing events in one call. This is why it returns a boolean value to indicate whether or not the GUI has finished processing.

You can read more about it in the (unfortunately out-of-date, ahem @void256 >_>) manual (event handling starts at page 69):
https://raw.githubusercontent.com/void256/nifty-gui/1.4/nifty-core/manual/nifty-gui-the-manual-1.3.2.pdf

P.S. For the time being, I'm going to assume that I have answered your question and close this issue. Feel free to repoen it if you have further concerns or if you discover a problem with the event handler.

**Closed as completed** 2015-01-06 05:26 UTC

**Comment by void256** [comment] 2015-01-06 21:33
Regarding the event handling and especially the boolean return parameter to mark an event as being processed ... erm ... it's not working like that anymore. A similar question has been asked by email and I'll just copy the answer here for your information:

Hi Itai,

sorry for the late response! Busy week :)

I think, I've found the reason for this behavior in this commit: https://github.com/void256/nifty-gui/commit/ace85d1  In the commit description there is a pretty long explanation why Nifty behaves this way. If you want you can read that for further explanation.

Here is a short summary:

Currently Nifty will always automatically consume events for the top-most element and won't process the event further. This appears to happen for the interact() methods as well as Nifty EventBus events. This is expected behavior and was explicitly added. Usually this is what you expect. You click something and the event will not process further down the element tree NOT hitting elements below it.

Actually I've tried to find a workaround for you but I have not been successful. Is this a big problem for you? I'm not sure we can change that easily tho :/

... // other stuff removed ...

Best regards,
Jens

**Comment by bgroenks96** [comment] 2015-01-06 21:53
@void256 Wait... so there is no way at all for the event to continue up the element hierarchy? I don't recall that change being introduced. That's a bit odd.

**Comment by void256** [comment] 2015-01-06 21:58
Just take a look at the commit and the commit comment referenced above.

**Comment by bgroenks96** [comment] 2015-01-06 22:51
> If you change your methods so that they would return a boolean you could stop that processing however. Just return true in the someMethod() on controller E and someMethod() will NOT be called on D,C,B or A.

Aha! So this is still valid for Controller hierarchies! I wasn't entirely wrong...

**Comment by void256** [comment] 2015-01-06 23:02
I'm not sure anymore if this is really true ... can you write a test case? I'll fix #303 in the meantime ... deal? :wink:

**Comment by bgroenks96** [comment] 2015-01-07 01:04
I'm busy having a deathmatch with Maven in changing the 2DX project structure at the moment :anguished: , but I will try to get on it soon! :smile:
