### ISSUE TITLE
both radio buttons in a group simultaneously active in a window

### ISSUE THREAD

**Issue by stephengold** [nifty-gui/nifty-gui#439] opened 2017-05-02 05:15 UTC
I've run into a situation where multiple radio buttons (in the same group) appear to be active at the same time. I'm using jMonkeyEngine 3.1.0-stable, which includes Nifty 1.4.2. Sample code attached.

[Main.java.txt](https://github.com/nifty-gui/nifty-gui/files/969486/Main.java.txt)
[Main.xml.txt](https://github.com/nifty-gui/nifty-gui/files/969487/Main.xml.txt)

**Comment by bgroenks96** [comment] 2017-06-11 15:06
Your XML is invalid. You never closed the `<control>` tag for the radio button group. Try fixing that and see if the issue still arises.

**Comment by stephengold** [comment] 2017-06-12 00:15
The control tag for the radio button group is self-closing. The indentation may have deceived your eye. I tried putting both radio buttons inside the group, but then they were not found by findNiftyControl().

**Comment by bgroenks96** [comment] 2017-06-12 03:42
Right, my mistake. Please provide a SSCE if you are able, [here](https://github.com/nifty-gui/nifty-gui-issues).

I'll look into it as soon as possible. Thanks.

**Comment by stephengold** [comment] 2017-06-12 18:56
What's an SSCE?

**Comment by bgroenks96** [comment] 2017-06-14 03:29
An SSCE is a short, simple, compile-able example. Basically just throw your example code into a simple test project that I can check out and run to verify/debug the problem. You can submit it as a pull request to the repo I linked to in the previous comment.

**Comment by stephengold** [comment] 2017-06-14 19:34
Is the example I provided on May 1st insufficient?

**Comment by bgroenks96** [comment] 2017-06-14 19:45
It would only compile and run in your development environment with JME set up, so no it's not sufficient.

The idea of an SSCE is that one can literally run `mvn clean compile` and then execute the resulting binaries to see the problem.

**Comment by stephengold** [comment] 2017-06-14 22:08
I don't use Maven, but I suppose I could learn ... Does NiftyGUI support JME, or doesn't it?

**Comment by bgroenks96** [comment] 2017-06-15 11:14
As of 1.4.2, JME is still supported.

You shouldn't really have to learn anything about Maven. It's already set up in Nifty. You can copy the `pom.xml` and any other necessary files from one of the other issues in the nifty-issues repo.

**Comment by stephengold** [comment] 2017-06-18 20:09
Note my pull request at https://github.com/nifty-gui/nifty-gui-issues

**Comment by bgroenks96** [comment] 2017-06-18 21:06
It seems from the example that the radio buttons only appear both selected when the screen is first loaded and then behave normally once you click on them. Is that consistent with your observations?

**Comment by bgroenks96** [comment] 2017-06-18 22:40
Ok, so firstly, and you might already be aware of this, the easy workaround to this problem is to simply move your `button.select()` call _after_ the `windowE.setVisible(true)`.

Long story short, the problem isn't with the internal logic of the radio button (or radio button group) but rather with the backing element's renderer defaulting to the "selected" image when the element is first drawn, thereby making it look like both radio buttons are selected.

I would like @void256 to comment on this, if possible. It's not a terribly important problem, imho, but it deserves at least some attention, if a quick fix is doable. We would need some way to force the element to use the correct image state when it's first drawn. Since the backing Element doesn't know anything about the radio button or its logic, it seems like the only way to address this would be to handle a "visibility" event in the radio button control and force the Element to change image states.

**Comment by stephengold** [comment] 2017-06-19 02:10
I'm glad you finally dug into this. Yes, the buttons behave correctly once you click on them. I worked around the bug in my current project, but I don't recall how exactly. Changing the order of events is much easier in an SSCE than in a big project.

**Comment by stephengold** [comment] 2017-06-24 22:12
I wonder how sliders and such deal with the initialization issue...

**Comment by stephengold** [comment] 2017-06-26 23:42
If I insert a third button between "default" and "bottom", it will not appear selected until I click on it. That suggests the backing element's renderer *isn't* defaulting to the "selected" image.

**Comment by bgroenks96** [comment] 2017-07-03 04:27
I am not able to reproduce that behavior. When I add a third radio button to your SSCE, the same behavior occurs.

XML:

    <panel childLayout="vertical">
            <control name="radioButtonGroup" id="group"/>
            <control name="radioButton" id="default" group="group"/>
            <control name="radioButton" id="middle" group="group"/>
            <control name="radioButton" id="bottom" group="group"/>
    </panel>

code:

        RadioButton button = screen.findNiftyControl("middle", RadioButton.class);
        button.select();
        windowE.setVisible(true);

**Comment by stephengold** [comment] 2017-07-03 04:53
"Same behavior" meaning all 3 buttons selected? Or just 2?

**Comment by bgroenks96** [comment] 2017-07-03 05:03
The last one to have `select()` called on it always shows up as selected, along with the first "default" radio button. The group logic appears to be behaving normally. The first radio button listed (i.e. the default to be selected) seems to be *deselected* and immediately *reselected* but _not by the control code_.

@void256 There's definitely something funky going on with the way the style/effect events are getting processed:

FINE: gotoScreenInternal [start]
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [window/window-close-button.png] uploaded to atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [radiobutton/radiobutton.png] uploaded to atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [radiobutton/radiobutton-checked.png] uploaded to atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [radiobutton/radiobutton-hover.png] uploaded to atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.Nifty subscribe
FINE: -> subscribe [group] screen [de.lessvoid.nifty.screen.Screen@6a668b14] -> [de.lessvoid.nifty.Nifty$ClassSaveEventTopicSubscriber@3e6085df{group}{de.lessvoid.nifty.controls.radiobutton.RadioButtonGroupControl$1@155e40cf}{class de.lessvoid.nifty.elements.events.ElementDisableEvent}(de.lessvoid.nifty.controls.radiobutton.RadioButtonGroupControl$1@155e40cf),(class de.lessvoid.nifty.elements.events.ElementDisableEvent)]
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.Nifty subscribe
FINE: -> subscribe [group] screen [de.lessvoid.nifty.screen.Screen@6a668b14] -> [de.lessvoid.nifty.Nifty$ClassSaveEventTopicSubscriber@4d7f62e{group}{de.lessvoid.nifty.controls.radiobutton.RadioButtonGroupControl$2@19e84ee0}{class de.lessvoid.nifty.elements.events.ElementEnableEvent}(de.lessvoid.nifty.controls.radiobutton.RadioButtonGroupControl$2@19e84ee0),(class de.lessvoid.nifty.elements.events.ElementEnableEvent)]
**Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage unloadImageFromAtlas
INFO: Image [radiobutton/radiobutton-checked.png] unloaded from texture atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage unloadImageFromAtlas
INFO: Image [radiobutton/radiobutton-hover.png] unloaded from texture atlas (atlas texture id: 1).**
BEFORE SELECT
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [radiobutton/radiobutton-checked.png] uploaded to atlas (atlas texture id: 1).
AFTER SELECT
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [radiobutton/radiobutton-hover.png] uploaded to atlas (atlas texture id: 1).
Jul 03, 2017 12:53:26 AM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [de/lessvoid/nifty/render/batch/nifty.png] uploaded to atlas (atlas texture id: 1).

I don't see any reason why the radio-button images should be loaded, unloaded, and then loaded again from the atlas.

**Comment by bgroenks96** [comment] 2017-07-03 05:58
@stephengold I found another peripheral cause to the problem. Removing your call to `windowE.setVisible(false)` (which I'm not sure why you needed anyway) resolves the issue. That call causes an unexpected chain of disposing/unloading of image resources from nifty's texture atlas _after_ the nifty runtime has already set everything up for rendering. I can't track down the exact cause of the wrong image reappearing, but it seems to be a mix-up in the image manager caused by the loading/unloading.

If you are making such spurious calls to `setVisible` in your application, I highly recommend that you remove them; telling Nifty to suddenly dispose of everything under the hood during initialization will just bring about all kinds of weird behavior.

**Comment by bgroenks96** [comment] 2017-07-03 06:08
I'm going to close this issue for the time being, as I can't find any evidence of defects in the backing control logic or in the renderer given *normal* initialization conditions. The image management bug caused by `setVisible` is worth noting, but it's not a normal (or formally defined) state for Nifty to be in on startup.

Please feel free to re-open the issue if you find anything else.

**Closed as completed by bgroenks96** 2017-07-03 06:08 UTC
Labels: wontfix

**Comment by stephengold** [comment] 2017-07-03 13:51
In my application I have dozens of permanent windows, which the user can select (make visible) as needed. Since windows are visible by default, I initialize each window to setVisible(false). I'm disappointed to learn that this is an unsupported feature.

**Comment by bgroenks96** [comment] 2017-07-03 13:59
Just make sure you don't call `setVisible(false)` until after everything has been initialized. And definitely don't call it if you are going to call `setVisible(true)` almost immediately afterward. 

If it continues to be a problem, please feel free to create a new issue for it.

**Comment by stephengold** [comment] 2017-07-03 14:55
What I'd like to avoid is having dozens of windows appear briefly during startup. What's an appropriate mechanism for invoking setVisible(false) after NiftyGUI has initialized but before the window could be displayed?

**Comment by bgroenks96** [comment] 2017-07-03 21:57
You should be OK to call `setVisible(false)` on the Window at the end of your control initialization, e.g. at the end of `onStartScreen` in the case of the SSCE. If I move the call to `setVisible(false)` to just before `setVisible(true)`, I don't see any issues. The window will appear as expected whenever you call `setVisible(true)` later on.
