### ISSUE TITLE
RFE: Support for Double-Click/Pointing at

### ISSUE THREAD

**Issue by mkaring** [nifty-gui/nifty-gui#53] opened 2012-09-24 07:36 UTC
Currently the Nifty-GUI only supports single mouse clicks, but it lacks the support for double clicks. So in case the user clicks twice on a location the single click function should **not** be executed, but the one for double clicks should be executed.

Furthermore it would be handy to have a pointing at functionality that is triggered one the user stops the mouse cursor on top of a element. This does only trigger in case the mouse cursor stops on the element, unlike the hover function that triggers already in case the mouse cursor moves over the new element.

**Comment by rhavin** [comment] 2013-02-07 14:38
Usually, on a doubleclick the singleclick-fn HAS to get executed first! In Windows – for example – if you douleclick, the first click selects the item (like a singleclick) and the second click executes it. Having items react to a singleclick other that to the first click of a doubleclick breaks users assumptions about GUIs. It would also make the GUI respond significantly slower, because it had to wait for the defined time of a doubleclick before it could execute any singleclick-event. I you really want your application to behave completely different on a singleclick than on the first click of a doubleclick – i'd strongly suggest not to do that – you could trigger a timer on first click that executes your code after a given time and have the doubleclick-handler remove the timer before it executes. But i state it again: it breaks users assumptions about GUIs.
Of course, modern mouses got a lot of keys (i've got 6) and there are also the modificator keys Ctrl and Shift, so if you really need that much of different behaviour, why not use them?

**Comment by philipwhiuk** [comment] 2013-07-13 22:48
> Furthermore it would be handy to have a pointing at functionality that is triggered one the user stops the mouse cursor on top of a element. This does only trigger in case the mouse cursor stops on the element, unlike the hover function that triggers already in case the mouse cursor moves over the new element.

This certainly isn't in the AWT events. There would have be some configurable timeout to determine how long a stop is. The normal behaviour is `mouseover`/`mouseout` (HTML), `mouseEnter`/`mouseExit` (AWT), `MouseEnter`/`MouseLeave` (WinForms)

**Comment by void256** [comment] 2014-04-27 10:10
relu91 added support for this now, see the commits referenced in the issue. Currently there is still a little issue with first click, see this commit for details: 9acfdf2da377ceb0b7a2bbc89467092bfb994c2d

I'll close this issue for now anyway!

**Closed as completed by void256** 2014-04-27 10:10 UTC

**Comment by relu91** [comment] 2014-04-30 11:34
Hi void , I've tried this morning but I can't reproduce that bug .... :tired_face: . What I did : ran control demo and start to click around but the focus change accordingly without click again , ran alldemomain and did the same thing , I didn't notice any strange behavior .http://www.youtube.com/watch?v=b_LQ1gOQjIE&feature=youtu.be short video about it . Should I misunderstood something?

**Comment by void256** [comment] 2014-04-30 22:08
No, you did not misunderstood. Here is my version of the video: https://www.youtube.com/watch?v=uecF0oQxVqI  Notice that in the beginning it does happen like everytime (it needs a second click), then it works and then near the end when I click the textfield at the bottom it requires a second click again. very very odd.

I'm using LWJGL and I'm on OS X. Maybe it's the combination of the two that is causing the issue?

When I rollback your commits then it works all the time tho o_O I've not yet really looked into your changes. Can you give me some hints where to start looking eventually?

**Comment by relu91** [comment] 2014-05-02 12:47
The main logic of my implementation is here : de.lessvoid.nifty.elements.ElementInteractionClickHandler . It is the first place where I'll looking for a bug . I'm afraid of it could be some time calculation issue . Here is the core of my code :

``` java
 if (onClickRepeatEnabled) {
      if (mouseInside && isMouseDown && isButtonDown) {
        long deltaTime = eventTime - mouseDownTime;
        if (deltaTime > REPEATED_CLICK_START_TIME) {
          long pastTime = deltaTime - REPEATED_CLICK_START_TIME;
          long repeatTime = pastTime - lastRepeatStartTime;
          if (repeatTime > REPEATED_CLICK_TIME) {
            lastRepeatStartTime = pastTime;
            if (onClickMouse(element.getId(), mouseEvent, canHandleInteraction, onClickAlternateKey)) {
              return true;
            }
          }
        }
      }
    }

```

This is the piece of code that I will debug . Sorry to annoying you with this ... I'll do some other test this afternoon anyway! .

**Comment by void256** [comment] 2014-05-02 20:12
I think the problem is this line https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/elements/ElementInteractionClickHandler.java#L79

I've added some log and that is the result:

```
eventTime: 1399060265108, lastClickTime: 0, deltaTime: -1099073388 => MULTI CLICK: 2
eventTime: 1399060267276, lastClickTime: 0, deltaTime: 2096822688 => INITIAL CLICK
```

If lastClickTime is 0 (as it is by default) we end up adding eventTime to deltaTime. But eventTime is a long and deltaTime is an int :wink: which will make deltaTime eventually overflow to a negative value. And we end up in the else branch interpreting the first click as a multi click ... which is my problem I think! :smile:

To fix it I've added that piece of code before line 79:

```
  if (lastClickTime == 0) {
    deltaTime = calculateThreshold() + 1;
  } else {
    deltaTime += eventTime - this.lastClickTime;
  }
```

which seems to fix the issue.

Can you take a look and please confirm if that is the issue? Maybe it's not only this but something else as well which I've overlooked?

**Comment by relu91** [comment] 2014-05-03 08:52
yes , you are right ! I don't think that there are something else , but have you tried to simple make deltatime long ? It should avoid the if-else block :smile: . Anyway on my pc it has never happened ....  quite wired ...

**Comment by void256** [comment] 2014-05-04 13:24
I've tried changing deltaTime to long at first but it didn't work. I'm not sure why because I think you're right :wink: It could be that I've changed other things as well because I've tried again with your original code AND long and it looks good to me now.

Well, it looks like so now at the very first click:

`eventTime: 1399209374913, lastClickTime: 0, deltaTime: 1399209374913 => INITIAL CLICK`

and it won't work in the very first milliseconds of 01.01.1970 too XD but I'll commit it now with "long" instead of my if solution. Simply because "if"s suck and it's always better to prevent them :smile:

I've left my debug output in (can be enabled with FINE log level if necessary) just in case.
