### ISSUE TITLE
both radio buttons in a group simultaneously active in a window

### ISSUE THREAD

**Issue by stephengold** [nifty-gui/nifty-gui#444] opened 2017-08-06 18:40 UTC
Issue #439 is not resolved for me, so I am opening a new issue per the advice of bgroenks96. I will submit a pull request to https://github.com/nifty-gui/nifty-gui-issues with a new SSCCE as soon as I have a new issue ID number.

**Comment by bgroenks96** [comment] 2017-08-06 18:57
What isn't resolved? Removing `setVisible(false)` didn't fix the issue?

**Comment by stephengold** [comment] 2017-08-07 01:25
I want my windows to be hidden at startup. If I remove setVisible(false), then the window is visible at startup. That's not an acceptable solution for me.

**Comment by bgroenks96** [comment] 2017-08-08 01:29
As it stands, this is a duplicate of #439. You need to either re-open that issue with an explanation of why the workaround doesn't suit you, and/or change the topic of this issue to reflect the behavior of windows on startup.

**Comment by stephengold** [comment] 2017-08-08 04:29
I've already explained why removing setVisible(false) doesn't suit me. I've enhanced the title of this issue to more closely reflect where I think the problem lies. Please study the SSCE I submitted to https://github.com/nifty-gui/nifty-gui-issues yesterday

Since the SSCE refers to issue #444, I'd prefer not to reopen #439.

**Comment by bgroenks96** [comment] 2017-08-09 02:53
The title of this issue is literally exactly the same as #439 word for word.

**Comment by bgroenks96** [comment] 2017-08-09 03:06
The issue is fixed in your SSCE using the exact same workaround I gave you in #439.

Configure the radio button in `onStartScreen` exactly how you did in the #439 SSCE, then call `setVisible(false)` _at the end_ of the method:

     @Override
    public void onStartScreen() {
        Window window = screen.findNiftyControl("window", Window.class);
        Element windowE = window.getElement();
        RadioButton button = screen.findNiftyControl("bottom", RadioButton.class);
        button.select();
        windowE.setVisible(false);
    }

Then call `setVisible(true)` normally in your `showWindow` method as you do already. No windows appear on startup, and the issue with the radio button's initial visual state does not occur.

**Comment by bgroenks96** [comment] 2017-08-24 04:16
Closing #444 as duplicate of #439

**Closed as completed by bgroenks96** 2017-08-24 04:16 UTC
Labels: duplicate
