### ISSUE TITLE
Creating SlickBatchRenderBackend breaks Slick2D's alpha blend functionality

### ISSUE THREAD

**Issue by arvyy** [nifty-gui/nifty-gui#432] opened 2016-08-22 19:20 UTC
![screenshot from 2016-08-22 22 11 35](https://cloud.githubusercontent.com/assets/15849668/17867995/78079a6c-68b5-11e6-93eb-bc3854f120da.png)

The only difference between these is in init method: 

```
    @Override
public void init(GameContainer gc, StateBasedGame sbg) throws SlickException {
    playField.setCenter(new Vector2f(gc.getWidth() / 2, gc.getHeight() / 2));
    SlickSlickInputSystem slickInputSystem = new SlickSlickInputSystem(this);
            //the one on the left has following line commented out and works properly.
    BatchRenderBackend renderer = SlickBatchRenderBackendFactory.create(gc);
    //FastTimeProvider timeProvider = new FastTimeProvider();
    //BatchRenderDevice batchRenderDevice = new BatchRenderDevice(renderer);
    //nifty = new Nifty(batchRenderDevice, new NullSoundDevice(), slickInputSystem, timeProvider);

}
```

The method that is using alpha blending is

```
 `protected void paintShadows(GameContainer gc, Graphics g){

    g.clearAlphaMap();
    g.setColor(shadowColor);
    g.setDrawMode(Graphics.MODE_ALPHA_MAP);
    for (Entity u : active) {
        if (hidden_units.contains(u)) continue;
        Shape s = u.getShadow();
        if (s != null)
            g.fill(s);
    }
    g.setDrawMode(Graphics.MODE_ALPHA_BLEND);

    g.setColor(shadowColor);
    g.fill(getScreenShapeOnWorld());
    g.setDrawMode(Graphics.MODE_NORMAL);


}`
```

**Comment by bgroenks96** [comment] 2016-08-23 17:22
Please provide a SSCE for verification and testing purposes, and I'll take a look as soon as possible.

You can submit the SSCE as a PR to [our issue repo](https://github.com/nifty-gui/nifty-gui-issues).

Thanks!

**Comment by arvyy** [comment] 2016-08-23 18:35
I didn't figure why it won't let me create a new pull request. I uploaded it here instead: https://github.com/arvyy/SlickNiftySSCE

**Comment by bgroenks96** [comment] 2016-08-24 02:03
Yeah I don't really understand what's going on with this code:

```
    @Override
    public void init(GameContainer gc) throws SlickException {
            BatchRenderBackend renderer = SlickBatchRenderBackendFactory.create(gc);
    }
```

You're creating a renderer, but it never gets passed into anything. I'm not sure what the output of this SSCE is supposed to look like, but I don't think it has anything to do with the nifty renderer in this particular case, unless I'm missing something here.

**Comment by arvyy** [comment] 2016-08-24 04:00
![screenshot from 2016-08-24 06 57 27](https://cloud.githubusercontent.com/assets/15849668/17917758/0b9c1c7c-69c8-11e6-9259-ccfaab98fd8d.png)

Again, renderer commented out on the instance on the left. 
What OS did you try it on? Maybe it is platform (Linux) specific.

**Comment by bgroenks96** [comment] 2016-08-25 01:08
Ok yeah, confirmed on Linux. I haven't tested on Windows (I don't have any development environment set up there), but I'll assume for now that it's probably not platform specific.

That's really bizarre that merely creating the batch render backend causes this. I'll look into it.

**Comment by bgroenks96** [comment] 2016-08-25 02:19
I found the [culprit](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/BatchRenderBackendInternal.java#L332).

If I had to guess, it's probably the call to change the alpha function. But it could be any one of those state changes.

Unfotunately, this isn't the kind of thing I can just rip out as a quick bug fix; changing the default blending mode might break a lot of other stuff unintentionally.

As a temporary workaround, you could grab the SlickGL instance out of the backend via reflection and make the appropriate calls to fix the GL state. Or you could set the blending mode/function via Slick if the API allows for that.

**Comment by void256** [comment] 2016-09-10 17:07
@bgroenks96 is right.

The problem is that at creation time of [BatchRenderBackendInternal](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/BatchRenderBackendInternal.java#L342) OpenGL alpha testing is being enabled and Slick2D does not use alpha testing at all. So Slick2D does not expose any public API to disable it again.

The workaround would be to disable it without help from Slick2D. We need to call LWJGL directly:

``` java
    import org.lwjgl.opengl.GL11;
...
    GL11.glDisable(GL11.GL_ALPHA_TEST);
```

I've just tried that with the SSCE (thanks for that @arvyy , very helpful!) as the first line in the `public void render(GameContainer gc, Graphics g) throws SlickException {` method which seems to fix the issue.

In general it's not a good idea to change GL state at creation time of any Nifty renderer I think. That's why the more modern BatchRenderBackendCoreProfileInternal doesn't do that anymore.

Looking back at it now the GL init was a bad design decision. It helps to set up everything quickly but GL setup belongs into the hands of the user and Nifty should only make sure to set it's state required for rendering when render() is called and preferable reset the state to whatever there was before. BatchRenderBackendCoreProfileInternal does that and we do the same in Nifty 2.0.

I'm hesitant to change that behaviour of BatchRenderBackendInternal at this point tho - mostly for historical reasons and I don't want to break any code that relies on that.

**Comment by bgroenks96** [comment] 2017-01-15 05:56
Please see above discussion for workarounds to this issue. Marking as closed.

**Closed as completed by bgroenks96** 2017-01-15 05:56 UTC
Labels: wontfix
