### ISSUE TITLE
nifty.createElementFromType() messes up sub-Templates

### ISSUE THREAD

**Issue by BorealFeast** [nifty-gui/nifty-gui#386] opened 2015-12-04 18:30 UTC
Hi there folks!

Normally I can solve the bugs I find in Nifty and propose a fix for them. That was until this issue. So what I'm trying to do is, like in the Listbox control, use the child of the child-root element as a template. The thing is that the template item is created successfully but the subsequent copies of the template are messed up. The duplicated control is well copied (at least that's what I found), but the template item that is the child of the duplicated control isn't even close to what is intended.

So here is my use case. I have this custom control that takes his first child and copies it to create a second child element using the ElementType of the first one. In my test case a made those elements some Lisboxes. This is what i'm try to create: ![Good](http://i.imgur.com/Soe64ZZ.png)

And this is what I get: 
![Bad](http://i.imgur.com/Q6Hyv0X.png)

As you can see, the second listbox is all messed up. The items seems to be in an absolute position in the screen. It even has the scrollbar control displayed.

I have attached my test case that is really simple. It's a maven project so pretty straightforward to run it.  All the logic is in the binding of the CustomController class and the layout is in the screen Interface/screen/main.xml. Nothing much. Maybe summoning @void256 will help me with this :grin: !
[NiftyTest.zip](https://github.com/void256/nifty-gui/files/52361/NiftyTest.zip)

**Comment by void256** [comment] 2015-12-17 15:56
I think this is one of the edge cases that aren't really supported.

Creating new elements in Controller bind() like you're trying to do, is reasonable from your (user) perspective but I don't think we'll get Nifty to do that correctly in that special case. Since bind() is probably called at a time when the layout of elements is already done your newly created element copy is probably not - if it is actually created correctly when being called in bind() the way you're doing it. Additionally, since it is a control there is a lot of resolving child elements, rearranging elements and so on going on inside of Nifty.

I would advise against using it this way - it will only lead to the dark side of Nifty - and there is a lot of darkness in 1.x :wink: I'm a bit sorry that these methods (accessing ElementType and similar classes/methods) ended up in the public API since for the most part they were only meant to be used by Nifty and called at the appropriate times.

Well, I've just modified your example by simply copying your template element (the listbox) a second time below your panel in your main.xml and giving it another id. And instead of making the copy inside of bind() I just access the second, already existing Listbox with getChildren().get(1) and everything works and looks as expected.

Another solution would be to create both Listbox controls on the fly from Java using Builders and don't use the XML as a "template" in that case at all.

I was experimenting a bit with your original code but I'm not sure where exactly the problem is (I suspect it is the way controls are being translated into actual simple elements somewhere in Nifty) but I don't see an easy way to modify Nifty or your example to support your use case.

**Comment by BorealFeast** [comment] 2015-12-17 16:16
As you said, I ended up by copying the template element (which is how I did to create the _expected_ Picture).
The thing is that it would lead to a messy xml, but wrapping the duplicated template into a control might be a good alternative.

**Closed as completed** 2016-01-11 20:46 UTC
