### ISSUE TITLE
OnStartHover and OnEndHover are not working properly when moving the mouse fast between hoverable elements

### ISSUE THREAD

**Issue by destroflyer** [nifty-gui/nifty-gui#412] opened 2016-02-12 19:18 UTC
I think the title is self-explaining, I described the issue more detailed in the jME forum:
http://hub.jmonkeyengine.org/t/mouse-events/18285/25?u=destroflyer

The behaviour worked in Nifty 1.3.3 (the one distributed with jME 3.0 Stable) and broke when upgrading to jME 3.1 Master, that uses Nifty 1.4.1.

**Comment by bgroenks96** [comment] 2016-02-13 07:17
Can you prepare a SSCE, please? Ideally one that isn't dependent on jME, but otherwise just make sure the Nifty related code is well separated so I can extract it. First thing to verify is that this is a Nifty core problem and not something specific to the jME input system implementation or something like that.

**Comment by destroflyer** [comment] 2016-02-13 16:35
Thanks for answering - You can download a test here:
http://destroflyer.mania-community.de/other/NiftyHoverTest.zip

It is a jME project, but it is really small - You can find an executable in the dist-directory. Hope, that helps.

**Comment by bgroenks96** [comment] 2016-02-13 19:59
Thanks. I've confirmed the issue occurs in the JOGL renderer as well. So the problem is definitely in Nifty core. We'll look into this ASAP.

**Comment by bgroenks96** [comment] 2016-02-13 21:01
It looks like the problem is that the onStartHover/onEndHover is only called once when the mouse initially enters your button panel. After that, `show` is not called until the mouse exits the buttons' parent panel (same goes for `hide`). So it has nothing to do with the speed of the mouse cursor, but rather the component logic for the effect.

Just to clarify, is your intention that `hide` should be called when the mouse leaves each button panel or when it leaves the parent panel?

**Comment by destroflyer** [comment] 2016-02-13 21:21
I think, the hide() method should be called even when moving the mouse from one button to the other.
For example, when moving from the left to the right:
show(0) -> hide() -> show(1) -> hide() -> show(2) -> hide()

The parent panel shouldn't have to do too much with the actual logic, since only the childs react to events (Not sure how it works internally, but only, if all hoverend and hoverstart events are called, you can expect a gui to work as planned I think).

**Comment by bgroenks96** [comment] 2016-02-13 21:47
Yes, I would agree. There's something screwy going on in the effect processor logic.

**Comment by bgroenks96** [comment] 2016-02-13 22:24
@void256 The two `EffectProccessor` instances for `OnHoverStart` and `OnHoverEnd` respectively are referencing different instances of the actual corresponding `Effect`, so `EffectManager` (or someone else) is actually creating _two_ Effect instances for the same effect and giving each of the different instances to the two processors. Thus, state isn't handled correctly because the two processors are talking past each other, so to speak. I'm having trouble finding where you wrote the code that might be responsible for passing the effect instances to the processors, though.

**Comment by void256** [comment] 2016-02-14 15:19
The whole event/effect processing in 1.x is ... a mess, unfortunately. It took me half a day to figure out what's happening :disappointed:

For a detailed description you should see the referenced commits.

Here is a short summarize:
1. Some long time ago we changed hover events to be marked as processed (like click events). The reason was to not send these events to other elements below the first one. This is reasonable. However, the onStartHover effect broke at that time. The reason was that we only send the mouse event to the elements currently under the mouse cursor AND stopped processing when the first element reported the event as processed which after the change happend for all hover events. The event was never send to the elements that are now not in hover state anymore and could therefore not been reset internally. The next time they were activated the onStartEffect method was not called because it was internally already marked as active. **Fix:** We now send these event to the elements that don't have the mouse over focus anymore which should fix the main problem of this issue. IMHO this was the intended behaviour anyway and someone just messed up `return` with `break` :wink:
2. The order of onStartHover and onEndHover was wrong. OnStartHover was called before onEndHover which is not the order one would expect. The problem here was that we did send the event first to the mouse over elements (which would activate the new hover effect) and after that to the elements without the mouse over state (which would deactivate the hover effect). Doing it in this order would execute the onStartHover effect first and the onEndHover effect last. I've now switched the order: the event is first send to the none-mouse over elements and after that to the mouse over elements. Since internally they all check the mouse position again this should be fine .. for most use cases. I'm not sure if this introduces other edge case problems tho.
3. The isMouseInside check was actually wrong when two elements - like in the example provided - were close to each other, sharing one edge. In that case it could be possible that both elements were marked as mouse over even tho they were not really overlapping which further complicated things. I've corrected the check now which did solve this problem as well.

@destroflyer Can you check this with 1.4.2-SNAPSHOT? It should be build automatically and available soon in the sf.net repo - or build it directly from source.

**Comment by destroflyer** [comment] 2016-02-14 17:19
Where exactly do i find the built snapshot? I can only find downloads up to 1.4.1., sorry, I don't know the sourceforge interface very well.

**Comment by bgroenks96** [comment] 2016-02-14 17:35
@void256 1.4.2-SNAPSHOT should just be the current state of the source tree correct? I've already tested this and confirmed that it's present when building from the 1.4 branch.

**Comment by bgroenks96** [comment] 2016-02-14 17:37
Oh, nevermind. I didn't see your new commits.

**Comment by void256** [comment] 2016-02-14 17:43
I have no idea what @bgroenks96 is trying to tell us :grinning: 

But you can find the latest SNAPSHOT build here: https://oss.sonatype.org/content/repositories/snapshots/com/github/nifty-gui/nifty/1.4.2-SNAPSHOT/

PS: Sorry, to mention sf.net - I already forgot that we're targeting a Maven central release with 1.4.2 and therefore snapshots are now hosted at Sonatypes SNAPSHOT repo!

**Comment by bgroenks96** [comment] 2016-02-14 17:49
I can verify that the fix worked with a fresh checkout of 1.4 and a modified version of the SSCE provided by @destroflyer (using JogAmp backend rather than jME).

**Comment by bgroenks96** [comment] 2016-02-14 17:55
Fix commits:
1d361e6
6f772b80

**Comment by destroflyer** [comment] 2016-02-14 19:22
Can confirm, the bug has been fixed. :)
It took me a while, since I had to create a new library to use in jME, but it was compatible with the jME code and the 1.4.1. default controls etc. (so I could just replace the *-1.4.1.jar and copy everything else).

Thanks for fixing this so quickly!

**Comment by void256** [comment] 2016-02-14 19:31
I added your example to the nifty-gui-issues project. So that it won't get lost if we ever need it again: https://github.com/nifty-gui/nifty-gui-issues/commit/93f9071b539f131e3fc129f7144b726125b59d1d
Thanks for reporting and confirming that it actually works :wink:
I'll close this issue now!

**Closed as completed by void256** 2016-02-14 19:31 UTC
